apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: sit722acremmalu.azurecr.io/customer-service:staging
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@customer-db:5432/customers"
      imagePullSecrets:
        - name: acr-secret
