apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sit722acremmalu.azurecr.io/product-service:staging
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@product-db:5432/products"
      imagePullSecrets:
        - name: acr-secret
