apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: production
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: sit722acremmalu.azurecr.io/customer-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@customer-db:5432/customers"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: production
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
