apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: production
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: sit722acremmalu.azurecr.io/order-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@order-db-service:5432/orders"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: production
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
